name: Aureliu Automation Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # Install dependencies and run tests
    - name: Run Maven Tests
      run: mvn clean test

    # Archive test reports
    - name: Archive Test Report
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: Test-Report
        path: target/surefire-reports/*
        retention-days: 1
